[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Wilder <friendwilder@yahoo.com.mx>"]

[tool.poetry.dependencies]
python = "3.7.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
